### ISSUE TITLE
[Feature Request] Some examples

### ISSUE THREAD

**Issue by adludum99** [ousnius/nifly#14]
Not an issue with your tool, but an issue with me. For some reason I appear to be stupid and I can't figure out how to use this tool. I'm trying to bulk convert nif static meshes to fbx. Maybe I'm really stupid and I don't even know what this tool is supposed to do. Well, let me know if
1. I can use your tool to accomplish what I need
2. how to accomplish what I need

Thanks!

**Comment by ousnius** [comment]
@adludum99 nifly doesn't include functionality to bulk convert to or from NIF. You will need to make use of the FBX SDK or assimp libraries to write such a thing yourself.
