### ISSUE TITLE
FO76 - NifFile::GetTextureSlot returning empty strings

### ISSUE THREAD

**Issue by SK83RJOSH** [ousnius/nifly#36]
Hello!

I know Fallout 76 isn't fully supported as of now, but I did some testing with a modified version of PyNifly and found most models, skeletons, and etc seem to load perfectly. The only issue I've come across so far is that texture are not populated correctly it seems. I'd be willing to toss a PR your way if you could give me some pointers on where to get started. 😄

**Comment by SK83RJOSH** [comment]
After a bit of digging, I see that this only affects nif files with a bgsm specified. Would loading these be out of scope for nifly? Even when these are specified, there's (always?) an accompanying BSShaderTextureSet specifying which textures to load. I'd be happy just to get those working for the time being.

**Comment by ousnius** [comment]
As you already noticed, FO76 doesn't carry proper texture set blocks in its NIF files. See #37 for my reply on that.
