### ISSUE TITLE
NifFile::Save removing/reordering strings in the header

### ISSUE THREAD

**Issue by xmusjackson** [ousnius/nifly#43]
As the title suggests, I'm having issues with the resulting nif file after running NifFile.Save(). I'm attempting to create a program which modifies a single header string and a few blocks in Fallout 4 nifs, but I'm stuck on the header.

From what I gather, the process for setting a header string is like so (please correct me if this is wrong):
```
nifly::NifFile nif;
nif.Load("some_nif.nif");

nif.GetHeader().SetStringById(some_id, some_string);

nif.Save("some_dst_nif.nif");
```

I've also tried applying save settings: 
```
nifly::NifSaveOptions opts = {false, false};
nif.Save("some_dst_nif.nif", opts);
```
Note: In the actual code I use if/ofstreams, but strings are used here for brevity.

'some_dst_nif.nif' not only doesn't contain the updated string, but somewhere in NifFile.Save() the header is being modified (Debugging is proving difficult because a lot of vars, especially hdr, are optimized out despite compiling both the lib and my binary with -O0). 

In my current test, the original Nif has 87 strings, and the target string has an ID of 13. While debugging, after executing `nif.GetHeader().SetStringByID(13, "A_New_String");`, the header shows as having the correctly updated string in position 13 of the NiString vector. 

However, after `nif.Save("some_dst_nif.nif")`, the header in memory shows as having only 38 strings. The target string is moved to position 22 and contains the contents of the target string before SetStringById(). The remaining strings were reordered as well. This is confirmed by opening the file in NifSkope, which also shows only 38 strings and does not reflect the change to the target string.

I'm new to the nif format so there may be some nuance I'm missing, but shouldn't this work, or is this to be expected? Opening and saving this nif without modifying the string results in the same output.  Am I doing something wrong?

I'll attach the input and output nifs here: 
[8Grids.zip](https://github.com/user-attachments/files/15842487/8Grids.zip)

**Comment by ousnius** [comment]
Yes, unused header strings are removed, which explains the decrease of the count. The leftover header strings are reordered (but their references everywhere adjusted).

So your NIF should work.

**Comment by xmusjackson** [comment]
Thanks for the clarification. I haven't actually tested the nif in game because of the second problem mentioned in the issue; When I run Save(), the string set by SetStringById does not appear to be affected in the resulting nif, the string remains unchanged although reordered. Any thoughts?

**Comment by ousnius** [comment]
> Thanks for the clarification. I haven't actually tested the nif in game because of the second problem mentioned in the issue; When I run Save(), the string set by SetStringById does not appear to be affected in the resulting nif, the string remains unchanged although reordered. Any thoughts?
> 
> Edit: After compiling the lib with -ggdb I was able to follow the header throughout execution. It seems the strings are being reset by `UpdateHeaderStrings()` at the end of `FinalizeData()`, which clears the strings if unknown blocks are not present and grabs the ones with references from the input file, negating the changes made to the header.

Ah yes. When loading the NIF, the strings are retrieved from the header and stored where they are used (in the block). So you need to change the string on the block(s) instead of using SetStringById on the header.

**Comment by xmusjackson** [comment]
> Ah yes. When loading the NIF, the strings are retrieved from the header and stored where they are used (in the block). So you need to change the string on the block(s) instead of using SetStringById on the header.

Following that advice I'm able to output a nif that contains the updated string. If it doesn't work in-game, that should exist in another issue, though I'll have to test tomrrow. Before I close this, however, I do have one question:

Why the decision to store the string with the data blocks? If they're pulled from the header and then pushed back into the header upon save, wouldn't it make more sense to keep the strings with the header and store references to the strings with the data blocks like the nif file itself does? (Not a pressing question really, more of a curiosity)

**Comment by ousnius** [comment]
> > Ah yes. When loading the NIF, the strings are retrieved from the header and stored where they are used (in the block). So you need to change the string on the block(s) instead of using SetStringById on the header.
> 
> Following that advice I'm able to output a nif that contains the updated string. If it doesn't work in-game, that should be discussed in a new issue, though I'll have to test tomorrow. Before I close this, however, I do have one question:
> 
> Why the decision to store the string with the data blocks? If they're pulled from the header and then pushed back into the header upon save, wouldn't it make more sense to keep the strings with the header and store references to the strings with the data blocks like the nif file itself does? (Not a pressing question really, more of a curiosity)

Storing the strings in the header has more of a file format and IO performance reason on the side of the NIF format. It also prevents storing the same strings over and over in duplicates.

Having them live in the class you're actually gonna be using with nifly makes more sense from an API standpoint (you don't have to keep mapping the IDs to get or update the right string in the header, you just do it once on save) and the extra memory usage from duplicating the strings in memory that way isn't relevant these days.

It also means that when you change a string (for example the name of a shape) on one block, it won't affect all other blocks that shared the same name (so shared the same string). You will receive a new string entry in the header on save.

This way you can just change the std::string in the API and not have to worry about changing all strings or adding a new string.

In the end it could be done either way, that's just how it ended up.

**Comment by xmusjackson** [comment]
That makes sense. Thanks for all the help and quick replies.
