### ISSUE TITLE
Added `textures\` at the end of texture path when texture path has trailing `\n`

### ISSUE THREAD

**Issue by Sebastian-81** [ousnius/nifly#49]
This was discovered by a user of [ParallaxGen](https://github.com/hakasapl/ParallaxGen)

If a shape has a `\n` at the end of a texture path in `BSShaderTextureSet`, Skyrim seems to just ignore it. Also NifSkope ignores it. Nifly adds a `textures\` at the end via this code: https://github.com/ousnius/nifly/blob/main/src/NifFile.cpp#L1172

This leads to a visual issue when the file is saved again and used in the game since the game can not find the texture anymore

**Comment by hakasapl** [comment]
Hi @ousnius , the fix may have broken other things, not 100% sure. I'm getting a `invalid string position` exception when loading some NIFs with the latest commit.

I've attached the NIF that I can reproduce with here. The exception occurs when calling `NifFile::Load()`

[winterholdtowerintwall01.zip](https://github.com/user-attachments/files/17268464/winterholdtowerintwall01.zip)

**Comment by ousnius** [comment]
@hakasapl Thanks for the find, it's fixed. It was caused by the file having texture paths containing just a blank space instead of being fully empty: " " instead of "". I added this case to the test as well.

**Comment by hakasapl** [comment]
Seems to fixed on my end as well for the latest commit - thank you!
