### ISSUE TITLE
request for reuse

### ISSUE THREAD

**Issue by SteveTownsend** [ousnius/nifly#7]
Hey, I have made a fork of this for use as a git submodule in a separate repository that adds C# adaptation via SWIG. I want to use that SWIG repository to output a Nuget package in support of a planned Synthesis patcher that updates NIF files.  I'd like to include a DLL built from my fork, and credit you, in my Nuget package. Is this OK? Thanks for the library.

**Comment by ousnius** [comment]
@SteveTownsend As long as it abides to the current license (see LICENSE file), credits and source code are provided and you try to make sure that any changes can easily be merged back (and forth!), I see no issue.

**Comment by SteveTownsend** [comment]
Sounds good - thanks.

My repos are https://github.com/SteveTownsend/nifly (the fork, with SWIG
conformance deltas) and https://github.com/SteveTownsend/niflyswig (NuGet
package source, GPL v3).

My nifly C++ code mods are pretty small in scope but as I tool out more of
the C# API it likely will expand. I was planning to not PR into your repo
unless you would prefer that.
